import Constants from 'expo-constants';
import { ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';

import { Button, ListRow } from '@/components/ui';

/** S-59 — version and the wellness disclaimer in full. Terms/privacy
 * policy/licences are placeholders: no legal copy has been drafted
 * yet, so the rows say that plainly rather than link somewhere fake. */
export default function AboutScreen() {
  const version = Constants.expoConfig?.version ?? '0.0.0';

  return (
    <SafeAreaView className="flex-1 bg-bg" edges={['top', 'bottom']}>
      <ScrollView className="flex-1 px-6 py-6" showsVerticalScrollIndicator={false}>
        <Text className="font-heading text-h3 text-text">About</Text>

        <Text className="mt-6 font-body text-body-sm text-neutral-400">
          Hunch is a self-tracking tool. It is not therapy, not medical advice, and not a crisis
          service. It runs small, honest experiments on your own data and tells you plainly what
          holds up — including when nothing does. Responses on written summaries are generated by
          software, not a person.
        </Text>

        <View className="mt-8">
          <ListRow label="Version" value={version} />
          <ListRow label="Terms of service" disabled />
          <ListRow label="Privacy policy" disabled />
          <ListRow label="Licences" disabled />
        </View>
        <Text className="mt-3 font-body text-caption text-neutral-500">
          Terms, privacy policy and licences have not been drafted yet.
        </Text>
      </ScrollView>
      <View className="px-6 pb-4">
        <Button label="Close" variant="ghost" onPress={() => router.back()} block />
      </View>
    </SafeAreaView>
  );
}
