import { useState } from 'react';
import { Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button, Chip } from '@/components/ui';
import { colors } from '@/design/tokens';
import { usersApi } from '@/features/users/usersApi';
import type { FocusArea } from '@/features/users/userTypes';
import { useAppDispatch, useAppSelector } from '@/store/hooks';

import { blockUnderAge, completeOnboarding } from './onboardingSlice';

type Step = 'welcome' | 'whatThisIsnt' | 'ageGate' | 'ageBlocked' | 'focusAreas' | 'health' | 'reminder';

const FOCUS_OPTIONS: Array<{ value: FocusArea; label: string }> = [
  { value: 'sleep', label: 'Why I sleep badly' },
  { value: 'movement', label: 'Why my energy crashes' },
  { value: 'mood', label: 'What affects my mood' },
];

const MIN_AGE = 17;

/**
 * S-01 through S-06, rendered as a plain component tree — not
 * file-based routes — so completion can't be navigated back into and
 * the under-17 terminal state has nowhere to "back" out of, matching
 * the spec's hard rule with no extra guard code needed. Budget: six
 * screens, under 90 seconds, ending in a completed first check-in
 * (the tabs shell, which takes over once this unmounts).
 */
export function OnboardingFlow() {
  const dispatch = useAppDispatch();
  const blockedUnderAge = useAppSelector((s) => s.onboarding.blockedUnderAge);
  const [step, setStep] = useState<Step>(blockedUnderAge ? 'ageBlocked' : 'welcome');
  const [birthMonth, setBirthMonth] = useState('');
  const [birthYear, setBirthYear] = useState('');
  const [ageError, setAgeError] = useState<string | null>(null);
  const [selectedAreas, setSelectedAreas] = useState<FocusArea[]>([]);

  const toggleArea = (value: FocusArea) => {
    setSelectedAreas((prev) => {
      if (prev.includes(value)) return prev.filter((v) => v !== value);
      if (prev.length >= 3) return prev;
      return [...prev, value];
    });
  };

  const handleAgeContinue = () => {
    const month = Number(birthMonth);
    const year = Number(birthYear);
    const now = new Date();
    const currentYear = now.getFullYear();

    if (
      !Number.isInteger(month) ||
      month < 1 ||
      month > 12 ||
      !Number.isInteger(year) ||
      year < 1920 ||
      year > currentYear
    ) {
      setAgeError('Enter a valid month and year.');
      return;
    }

    setAgeError(null);
    // Month-precision age check: treat "17 by this point in the year"
    // as old enough, matching a plain month+year birth date collection.
    const turns17ThisYear = currentYear - year;
    const hasHadBirthdayThisYear = now.getMonth() + 1 >= month;
    const age = hasHadBirthdayThisYear ? turns17ThisYear : turns17ThisYear - 1;

    if (age < MIN_AGE) {
      dispatch(blockUnderAge());
      setStep('ageBlocked');
      return;
    }
    setStep('focusAreas');
  };

  const handleFinish = async () => {
    try {
      if (selectedAreas.length > 0) {
        await usersApi.replaceFocusAreas({ focusAreas: selectedAreas });
      }
    } catch {
      // Onboarding must complete offline too (G-1) — focus areas sync
      // opportunistically; a network failure here never blocks setup.
    }
    dispatch(completeOnboarding());
  };

  if (step === 'ageBlocked') {
    return (
      <Screen>
        <Text className="text-center font-heading text-h4 text-text">
          This app is not built for people under 17.
        </Text>
        <Text className="mt-3 text-center font-body text-body-sm text-neutral-400">
          If you are struggling, support resources can help even without using this app.
        </Text>
      </Screen>
    );
  }

  if (step === 'welcome') {
    return (
      <Screen cta="Start" onCta={() => setStep('whatThisIsnt')}>
        <Text className="font-heading text-h2 text-text">
          Most health apps track you. This one runs experiments.
        </Text>
        <Text className="mt-4 font-body text-body text-neutral-400">
          It watches your sleep, movement and mood, finds what actually moves them, then tests it
          for two weeks and tells you whether it worked. Including when it did not.
        </Text>
        <Text className="mt-8 font-body text-caption text-neutral-600">
          Responses are generated by software, not a person.
        </Text>
      </Screen>
    );
  }

  if (step === 'whatThisIsnt') {
    return (
      <Screen cta="I understand" onCta={() => setStep('ageGate')}>
        <Text className="font-heading text-h3 text-text">Before you start.</Text>
        <Text className="mt-4 font-body text-body text-neutral-400">
          This is a self-tracking tool. It is not therapy, not medical advice, and not a crisis
          service.
        </Text>
        <Text className="mt-3 font-body text-body text-neutral-400">
          It will not diagnose anything or tell you what a symptom means. If it does not have the
          data to answer something, it will say so.
        </Text>
        <Text className="mt-3 font-body text-body text-neutral-400">
          If you are in crisis or thinking about harming yourself, please reach out to someone now.
        </Text>
      </Screen>
    );
  }

  if (step === 'ageGate') {
    return (
      <Screen cta="Continue" onCta={handleAgeContinue}>
        <Text className="font-heading text-h3 text-text">How old are you?</Text>
        <Text className="mt-2 font-body text-body-sm text-neutral-400">
          This app is for adults. You need to be 17 or older.
        </Text>
        <View className="mt-6 flex-row gap-3">
          <TextInput
            value={birthMonth}
            onChangeText={setBirthMonth}
            placeholder="MM"
            placeholderTextColor={colors.neutralRamp[600]}
            keyboardType="number-pad"
            maxLength={2}
            className="flex-1 rounded-default border border-neutral-700 px-3 py-3 font-body text-body text-text"
          />
          <TextInput
            value={birthYear}
            onChangeText={setBirthYear}
            placeholder="YYYY"
            placeholderTextColor={colors.neutralRamp[600]}
            keyboardType="number-pad"
            maxLength={4}
            className="flex-1 rounded-default border border-neutral-700 px-3 py-3 font-body text-body text-text"
          />
        </View>
        {ageError && <Text className="mt-2 font-body text-caption text-neutral-400">{ageError}</Text>}
      </Screen>
    );
  }

  if (step === 'focusAreas') {
    return (
      <Screen cta="Continue" ctaDisabled={selectedAreas.length === 0} onCta={() => setStep('health')}>
        <Text className="font-heading text-h3 text-text">What do you want to understand?</Text>
        <Text className="mt-2 font-body text-body-sm text-neutral-400">
          Pick up to three. You can change these later.
        </Text>
        <View className="mt-6 flex-row flex-wrap gap-2">
          {FOCUS_OPTIONS.map((option) => (
            <Chip
              key={option.value}
              label={option.label}
              selected={selectedAreas.includes(option.value)}
              disabled={selectedAreas.length >= 3 && !selectedAreas.includes(option.value)}
              onPress={() => toggleArea(option.value)}
            />
          ))}
        </View>
      </Screen>
    );
  }

  if (step === 'health') {
    return (
      <Screen cta="Skip, I will enter things myself" onCta={() => setStep('reminder')}>
        <Text className="font-heading text-h3 text-text">Connect health data?</Text>
        <Text className="mt-2 font-body text-body-sm text-neutral-400">
          Sleep and activity permissions are not wired up yet, you can add this later from
          Settings. For now, everything works fine entered by hand.
        </Text>
      </Screen>
    );
  }

  // reminder
  return (
    <Screen cta="Finish setup" onCta={() => void handleFinish()}>
      <Text className="font-heading text-h3 text-text">When do you want to check in?</Text>
      <Text className="mt-2 font-body text-body-sm text-neutral-400">
        Most people do this just before bed. Reminder scheduling is not wired up yet, you will be
        able to set this from Settings once it lands.
      </Text>
    </Screen>
  );
}

function Screen({
  children,
  cta,
  ctaDisabled,
  onCta,
}: {
  children: React.ReactNode;
  cta?: string;
  ctaDisabled?: boolean;
  onCta?: () => void;
}) {
  return (
    <SafeAreaView className="flex-1 bg-bg" edges={['top', 'bottom']}>
      <View className="flex-1 justify-center px-8">{children}</View>
      {cta && (
        <View className="px-8 pb-6">
          <Button label={cta} onPress={onCta ?? (() => {})} disabled={ctaDisabled} block />
        </View>
      )}
    </SafeAreaView>
  );
}
